
import React, { ReactNode } from 'react';

interface AiInsightCardProps {
  title: string;
  insight: string;
  severity: 'success' | 'warning' | 'error' | 'info';
  icon?: ReactNode;
}

const AiInsightCard = ({ title, insight, severity, icon }: AiInsightCardProps) => {
  const severityColors = {
    success: '#2ecc71',
    warning: '#f39c12',
    error: '#e74c3c',
    info: '#3498db'
  };
  
  const cardStyle = {
    backgroundColor: 'white',
    borderRadius: '8px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.05)',
    padding: '1.5rem',
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100%',
    borderTop: `3px solid ${severityColors[severity]}`
  };
  
  const titleStyle = {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '1rem',
    color: '#555',
    fontWeight: '600' as const
  };
  
  const insightStyle = {
    fontSize: '1rem',
    color: '#333',
    lineHeight: 1.5
  };
  
  return (
    <div style={cardStyle}>
      <div style={titleStyle}>
        {icon && React.cloneElement(icon as React.ReactElement, { color: severityColors[severity] })}
        {title}
      </div>
      <div style={insightStyle}>{insight}</div>
      <div style={{marginTop: 'auto', paddingTop: '1rem', borderTop: '1px solid #f0f0f0', fontSize: '0.85rem', color: '#888'}}>
        Generated by AI from recent financial data
      </div>
    </div>
  );
};

export default AiInsightCard;
